controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
